driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/aapp']

provisioner:
  name: chef_zero

platforms:
  - name: centos-7

suites:
  - name: default
    run_list: OMNIBUS::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/aapp
  - name: test
