driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/aapp']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
  - name: centos-6.8
    run_list: ['yum-epel::default', 'packages']
    attributes:
      packages-cookbook: [ 'ksh', 'gcc-gfortran', 'libgfortran' ]
suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/aapp
